### ISSUE TITLE
Process multiple dimensions

### ISSUE THREAD

**Issue by deanhume** [bezoerb/grunt-critical#11]
Hi

I am trying to process multiple dimensions against a single HTML file like so:

    critical: {
			dist: {
				options: {
					base: './',
					dimensions: [{
						width: 1300,
						height: 900
					},
					{
						width: 500,
						height: 900
					}]
				},
				files: [
				{src: ['index-critical.html'], dest: 'index.html'}
				]
			}
		}

But I get the following code inlined:

    <style type="text/css">
        [object Object]
    </style>

Any ideas?

**Comment by bezoerb** [comment]
I'll take a look later today.
Thanks for reporting

**Comment by bezoerb** [comment]
@deanhume just wrote a testcase using the `dimensions` option and everything seems good.
Can you provide some more context?
Maybe try `rm -Rf node_modules && npm install`?

**Comment by deanhume** [comment]
@bezoerb Thanks for your help. Unfortunately I am still getting that same error even after removing as you suggested. 

I am actually processing it against this particular file:

https://github.com/deanhume/typography/blob/gh-pages/index-critical.html 

and using the exact code in my gruntfile as mentioned above. Everything else seems good on the page, its just the inlining that doesn't seem to work and gives me HTML like so:

    <style type="text/css">
        [object Object]
    </style>

**Comment by deanhume** [comment]
@bezoerb I've had a look at your test case and it seems to work. I have no idea why my particular version won't work!

**Comment by bezoerb** [comment]
can you post the output of `npm list` to a gist?
Maybe there are some conflicting versions

**Comment by deanhume** [comment]
Not sure if this helps - https://gist.github.com/1a1df257ce356d274126.git

Please let me know if you need it in another format - thank you!

**Comment by bezoerb** [comment]
looks like the wrong list.
It should list all the npm packages within your failing project. This list doesn't contain grunt-critical at all ;)

**Comment by bezoerb** [comment]
you should run this command inside your project root

**Comment by deanhume** [comment]
Okay, Ive updated that Gist - let me know if you need more information.

**Comment by bezoerb** [comment]
This looks like a version mismatch with `clean-css`
As of version 3.x a hash is returned instead of the minified css string. So maybe there's something on this side. I'll take a look at the new gist

**Comment by deanhume** [comment]
Awesome - thank you @bezoerb

**Comment by bezoerb** [comment]
Hmm,... nothing conspicuous inside your gist,... 
Need deeper ls.
`npm ls --depth=10 | grep "grunt-critical" -A 60` or
`npm ls --depth=10 | grep "clean-css" -C 50`

The cleancss version used by critical needs be somewhere around `2.2.23`

**Comment by deanhume** [comment]
Okay - Gist updated. Unfortunately I am running on Windows, so I cant grep - but let me know if that works for you!

**Comment by bezoerb** [comment]
Now this looks wrong. 
```shell
  grunt-critical@0.1.2
  └─┬ critical@0.5.6
    ├── clean-css@3.1.9
    └─┬ inline-critical@0.1.2
      └── clean-css@3.1.8
```

this should be
```shell
  grunt-critical@0.1.2
  └─┬ critical@0.5.6
    ├── clean-css@2.2.23
    └─┬ inline-critical@0.1.2
      └── clean-css@3.1.8
```

**Comment by bezoerb** [comment]
@deanhume we've just landed a new release of `critical` with bumped dependencies.
Could you try again with a fresh install?
`npm cache clean`
`rm -Rf node_modules` (or remove the folder on windows ^^)
`npm install`

**Comment by deanhume** [comment]
:boom: That's the one - all sorted!

Thanks so much for your help! :smile:
