### ISSUE TITLE
Update to Critical 0.7.0 ?

### ISSUE THREAD

**Issue by ethyde** [bezoerb/grunt-critical#19]
Hi,

Can you update to use critical version 0.7.0, and explain how to use this feature https://github.com/addyosmani/critical/pull/100 in a Grunt task ? :)

Thanks a lot.

**Comment by macx** [comment]
:+1:

**Comment by bezoerb** [comment]
https://github.com/bezoerb/grunt-critical/releases/tag/v0.2.0
You can use an url as src in your grunt task:
```javascript
grunt.initConfig({
    critical: {
        remote: {
            src: 'http://some.domain.com',
            dest: 'critical.css'
        }
    }
});

**Comment by ethyde** [comment]
It's working great ! 

Thanks :)
