### ISSUE TITLE
Critical CSS don't see JS

### ISSUE THREAD

**Issue by shervud** [bezoerb/grunt-critical#42]
Hello everyone.
As I quite clear understand, grunt-critical is a shell over critical module (https://github.com/addyosmani/critical) which based on penthouse module (https://github.com/pocketjoso/penthouse).
So as I see Penthouse has options to work with JS, they are: **renderWaitTime** and **blockJSRequests**. But grunt-critical does not. 
My questions is: does grunt-critical proceed html page and produce critical CSS including styles which were inserted/appended by JavaScript.
**For example**
**my css file is:**
.my-class{...}
.classss{...}
**My source html is the following:**
< div class="my-class">< span>qwe</ span></ div>

**After proceeding DOM html by JavaScript html code is going to be the following:**
< div class="classss my-class">< span>qwe</ span></ div>

**So , i'd like to** get critical css by grunt-critical which will has .my-class and .classss. But now it's only getting .my-class

**Comment by bezoerb** [comment]
@shervud: You can pass options to penthouse like this:
```js
critical': {
  options: {
    base: 'mybasepath',
    penthouse: {
      renderWaitTime: ...
    }
  },
  src: '...',
  dest: '...'
},
```

**Comment by shervud** [comment]
Yep, thank you, I have already got it ;)
