### ISSUE TITLE
1.0.1 - various errors

### ISSUE THREAD

**Issue by jjshabadoo** [bezoerb/grunt-critical#45]
Using node 8.9.0

Initially I had issues with 1.0.0 as in here:  https://github.com/addyosmani/critical/issues/218. 

I applied yawlhead91's fix and grunt-critical ran at without any error messages.

Now using the write to css file option, I do get some css in there but not anything critical. Write to an html file overwrites the html file completely with that same css.

I attempted to downgrade to v0.2.2 as suggested elsewhere, still with errors. 

Anyone else seeing this? Any info I can provide which would help? Thanks

**Comment by bezoerb** [comment]
This should be fixed in critical [v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.1.0). 
I'll bump `grunt-critical` in the next days

**Comment by jjshabadoo** [comment]
Thx for the quick reply!

**Comment by bezoerb** [comment]
https://github.com/bezoerb/grunt-critical/releases/tag/v1.1.0

**Comment by jjshabadoo** [comment]
Working like a charm now. Thanks!
