### ISSUE TITLE
Warning: critical.generate

### ISSUE THREAD

**Issue by artqvo** [bezoerb/grunt-critical#47]
I'm getting this error:

> Running "critical:test" (critical) task
> Warning: critical.generate(...).then(...).error is not a function Use --force to continue.

My configuration:
```
// Critical CSS test case
    critical: {
      test: {
        options: {
            base: './',
            css: [
                'bower_components/bootstrap/dist/css/bootstrap.min.css',
                'dist/css/msssi-app.min.css',
                'dist/css/skins/skin-msssi.min.css'
            ],
            width: 1300,
            height: 900
        },
        src: 'index.html',
        dest: 'index-critical.html',
      }
```
Sorry, if this is a very lame error, I'm quite new at this.

**Comment by nfrankel** [comment]
+1

**Comment by lt7** [comment]
+1

**Comment by hctom** [comment]
Same issue here. The related PR fixes the issue, but unfortunately the builds fail there. Perhaps one of the maintainers may have a look at it, so this package can be used again.

**Comment by bezoerb** [comment]
sorry for the late response.
PR is merged & new version is released:
https://github.com/bezoerb/grunt-critical/releases/tag/v1.1.1

**Comment by artqvo** [comment]
Thanks
