### ISSUE TITLE
Self closing Tags / SVG

### ISSUE THREAD

**Issue by jjshabadoo** [bezoerb/grunt-critical#53]
Hello,

Having trouble with svg's - I assume the issue is self closing tags.

I've seen this was addressed years ago in critical / cheerio and those are marked as closed. Have not had this in previous experience with this module. Any suggestions for a fix with current version?

This:

`<symbol viewBox="0 0 24 24" id="shape-clock">
		<title>clock</title>
		<path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z" />
		<path d="M0 0h24v24H0z" fill="none" />
		<path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z" />
	</symbol>`

Becomes this: 

`<symbol viewbox="0 0 24 24" id="shape-clock">
			<title>clock</title>
			<path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z">
				<path d="M0 0h24v24H0z" fill="none">
					<path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z"> </path>
				</path>
			</path>
		</symbol>`

Thnaks

**Comment by bezoerb** [comment]
@jjshabadoo: Can you check which version of inline-critical is used in your project?
I've just added a test for your failing svg and the output was just as expected.
https://github.com/bezoerb/inline-critical/commit/c10a6a2bfd6e7e9954c7c57bf2f1dc34db106fc0

**Comment by jjshabadoo** [comment]
└─┬ grunt-critical@1.1.1
  └─┬ critical@1.3.4
    └── inline-critical@4.0.5

**Comment by jjshabadoo** [comment]
Updated all my modules and I am not seeing this issue any longer. Thanks
