### ISSUE TITLE
grunt-critical hanging

### ISSUE THREAD

**Issue by khalwat** [bezoerb/grunt-critical#8]
I've used grunt-critical to great success on some projects already (thank you!), but in moving an existing site over to grunt-critical, I've encountered a problem.

I run grunt critical, and it just hangs.  I've left it running for hours, to no avail, it just sits there churning up 100% of CPU.  If I interrupt the task with ^C, there are tmp-4073j10r0cw.css files sitting in the build directory that appear to be the correct inline CSS.

Here's what the grunt task looks like:

		critical: {
		    site_index: {
		        options: {
		            base: '<%= pkg.dist_path %>',
		            css: [
		                '<%= pkg.dist_path %>css/site.combined.min.css',
		            ],
		            width: 960,
		            height: 900
		        },
		        src: '<%= pkg.build_path %>html/site_index.html',
		        dest: '<%= pkg.dist_path %>css/site_index_critical.min.css'
		    },

In package.json:

	  "dist_path": "",
	  "build_path": "build/",
	  "template_path": "../templates/default_site/",
	  "site_url": "http://www.CrushLivePoker.com/",

What I do is I have a separate grunt curl task that curls the site_index into <%= pkg.build_path %>html/site_index.html so that it's cached; you can see that static HTML file here:

http://www.crushlivepoker.com/site/build/html/site_index.html

I also point it to the CSS locally, rather than having it parse through the HTML, because I load everything via a CDN, async with loadCSS().  It also just seemed cleaner.  Here's the URL to the CSS file it parses against:

http://www.crushlivepoker.com/site/css/site.combined.min.css

For completeness, here's the npm list of the grunt-critical task I have installed:

	├─┬ grunt-critical@0.0.4
	│ ├── async@0.9.0
	│ └─┬ critical@0.5.2
	│   ├── bluebird@2.6.4
	│   ├─┬ cheerio@0.17.0
	│   │ ├─┬ CSSselect@0.4.1
	│   │ │ ├── CSSwhat@0.4.7
	│   │ │ └─┬ domutils@1.4.3
	│   │ │   └── domelementtype@1.1.3
	│   │ ├─┬ dom-serializer@0.0.1
	│   │ │ └── domelementtype@1.1.3
	│   │ ├── entities@1.1.1
	│   │ └─┬ htmlparser2@3.7.3
	│   │   ├── domelementtype@1.1.3
	│   │   ├── domhandler@2.2.1
	│   │   ├── domutils@1.5.0
	│   │   ├── entities@1.0.0
	│   │   └─┬ readable-stream@1.1.13
	│   │     ├── core-util-is@1.0.1
	│   │     ├── inherits@2.0.1
	│   │     ├── isarray@0.0.1
	│   │     └── string_decoder@0.10.31
	│   ├─┬ clean-css@2.2.23
	│   │ └── commander@2.2.0
	│   ├─┬ cli@0.6.5
	│   │ ├── exit@0.1.2
	│   │ └─┬ glob@3.2.11
	│   │   ├── inherits@2.0.1
	│   │   └─┬ minimatch@0.3.0
	│   │     ├── lru-cache@2.5.0
	│   │     └── sigmund@1.0.0
	│   ├── get-stdin@3.0.2
	│   ├─┬ imageinliner@0.2.3
	│   │ ├── css-parse@1.7.0
	│   │ ├─┬ css-stringify@1.4.1
	│   │ │ └─┬ source-map@0.1.43
	│   │ │   └── amdefine@0.1.0
	│   │ ├── mime@1.2.11
	│   │ ├── mkdirp@0.3.5
	│   │ ├─┬ optimist@0.6.1
	│   │ │ ├── minimist@0.0.10
	│   │ │ └── wordwrap@0.0.2
	│   │ └── underscore@1.7.0
	│   ├─┬ indent-string@1.2.0
	│   │ ├── minimist@1.1.0
	│   │ └─┬ repeating@1.1.1
	│   │   └── is-finite@1.0.0
	│   ├─┬ inline-critical@0.0.9
	│   │ ├─┬ cave@2.0.0
	│   │ │ ├─┬ css@2.1.0
	│   │ │ │ ├── inherits@2.0.1
	│   │ │ │ ├─┬ source-map@0.1.43
	│   │ │ │ │ └── amdefine@0.1.0
	│   │ │ │ ├─┬ source-map-resolve@0.3.1
	│   │ │ │ │ ├── atob@1.1.2
	│   │ │ │ │ ├── resolve-url@0.2.1
	│   │ │ │ │ └── source-map-url@0.3.0
	│   │ │ │ └── urix@0.1.0
	│   │ │ └── minimist@1.1.0
	│   │ ├─┬ normalize-newline@1.0.1
	│   │ │ └── minimist@1.1.0
	│   │ ├─┬ reaver@1.2.0
	│   │ │ └── minimist@1.1.0
	│   │ └─┬ uglify-js@2.4.16
	│   │   ├── async@0.2.10
	│   │   ├─┬ optimist@0.3.7
	│   │   │ └── wordwrap@0.0.2
	│   │   ├─┬ source-map@0.1.34
	│   │   │ └── amdefine@0.1.0
	│   │   └── uglify-to-browserify@1.0.2
	│   ├── lodash@2.4.1
	│   ├─┬ meow@2.1.0
	│   │ ├─┬ camelcase-keys@1.0.0
	│   │ │ ├── camelcase@1.0.2
	│   │ │ └── map-obj@1.0.0
	│   │ ├── minimist@1.1.0
	│   │ └── object-assign@2.0.0
	│   ├── object-assign@1.0.0
	│   ├─┬ oust@0.2.3
	│   │ ├─┬ cheerio@0.18.0
	│   │ │ ├─┬ CSSselect@0.4.1
	│   │ │ │ ├── CSSwhat@0.4.7
	│   │ │ │ └─┬ domutils@1.4.3
	│   │ │ │   └── domelementtype@1.1.3
	│   │ │ ├─┬ dom-serializer@0.0.1
	│   │ │ │ └── domelementtype@1.1.3
	│   │ │ ├── entities@1.1.1
	│   │ │ └─┬ htmlparser2@3.8.2
	│   │ │   ├── domelementtype@1.1.3
	│   │ │   ├── domhandler@2.3.0
	│   │ │   ├── domutils@1.5.0
	│   │ │   ├── entities@1.0.0
	│   │ │   └─┬ readable-stream@1.1.13
	│   │ │     ├── core-util-is@1.0.1
	│   │ │     ├── inherits@2.0.1
	│   │ │     ├── isarray@0.0.1
	│   │ │     └── string_decoder@0.10.31
	│   │ └── minimist@1.1.0
	│   ├─┬ penthouse@0.2.51
	│   │ ├─┬ nopt@3.0.1
	│   │ │ └── abbrev@1.0.5
	│   │ └─┬ phantomjs@1.9.13
	│   │   ├── adm-zip@0.4.4
	│   │   ├── kew@0.4.0
	│   │   ├─┬ mkdirp@0.5.0
	│   │   │ └── minimist@0.0.8
	│   │   ├── ncp@1.0.1
	│   │   ├─┬ npmconf@2.0.9
	│   │   │ ├─┬ config-chain@1.1.8
	│   │   │ │ └── proto-list@1.2.3
	│   │   │ ├── inherits@2.0.1
	│   │   │ ├── ini@1.3.2
	│   │   │ ├─┬ once@1.3.1
	│   │   │ │ └── wrappy@1.0.1
	│   │   │ ├── osenv@0.1.0
	│   │   │ ├── semver@4.2.0
	│   │   │ └── uid-number@0.0.5
	│   │   ├── progress@1.1.8
	│   │   ├─┬ request@2.42.0
	│   │   │ ├── aws-sign2@0.5.0
	│   │   │ ├─┬ bl@0.9.3
	│   │   │ │ └─┬ readable-stream@1.0.33
	│   │   │ │   ├── core-util-is@1.0.1
	│   │   │ │   ├── inherits@2.0.1
	│   │   │ │   ├── isarray@0.0.1
	│   │   │ │   └── string_decoder@0.10.31
	│   │   │ ├── caseless@0.6.0
	│   │   │ ├── forever-agent@0.5.2
	│   │   │ ├─┬ form-data@0.1.4
	│   │   │ │ ├─┬ combined-stream@0.0.7
	│   │   │ │ │ └── delayed-stream@0.0.5
	│   │   │ │ └── mime@1.2.11
	│   │   │ ├─┬ hawk@1.1.1
	│   │   │ │ ├── boom@0.4.2
	│   │   │ │ ├── cryptiles@0.2.2
	│   │   │ │ ├── hoek@0.9.1
	│   │   │ │ └── sntp@0.2.4
	│   │   │ ├─┬ http-signature@0.10.1
	│   │   │ │ ├── asn1@0.1.11
	│   │   │ │ ├── assert-plus@0.1.5
	│   │   │ │ └── ctype@0.5.3
	│   │   │ ├── json-stringify-safe@5.0.0
	│   │   │ ├── mime-types@1.0.2
	│   │   │ ├── node-uuid@1.4.2
	│   │   │ ├── oauth-sign@0.4.0
	│   │   │ ├── qs@1.2.2
	│   │   │ ├── stringstream@0.0.4
	│   │   │ ├─┬ tough-cookie@0.12.1
	│   │   │ │ └── punycode@1.3.2
	│   │   │ └── tunnel-agent@0.4.0
	│   │   ├─┬ request-progress@0.3.1
	│   │   │ └── throttleit@0.0.2
	│   │   ├── rimraf@2.2.8
	│   │   └── which@1.0.8
	│   ├── slash@1.0.0
	│   └── tmp@0.0.24

**Comment by khalwat** [comment]
Still hung up on this (no pun intended).  No useful information comes out if I do:

    grunt critical --verbose --debug

    Running "critical" task
    [D] Task source: /var/www/clp/site/node_modules/grunt-critical/tasks/critical.js

     Running "critical:site_index" (critical) task
    [D] Task source: /var/www/clp/site/node_modules/grunt-critical/tasks/critical.js
     Verifying property critical.site_index exists in config...OK
     Files: build/html/site_index.html -> css/site_index_critical.min.css
     Options: base="", css=["css/site.combined.min.css"], width=960, height=900

**Comment by bezoerb** [comment]
hey @khalwat 
sorry for the late response. 
I've quite busy at the moment but i will try to take a look at this issue tomorrow.

**Comment by khalwat** [comment]
No worries at all, I appreciate your time.  I do have developmental experienced (C/PHP, etc.) and am willing to help in any way I can.  I can't really determine what about the HTML it doesn't like... or whether it is critical or penthouse or phantomjs that is hanging.

But you should be able to replicate it locally, given the static files listed in the Gruntfile above.

**Comment by khalwat** [comment]
So I figured it out by process of elimination.  There's a chunk of Javascript code that I inline (just RequireJS + my config JS for it) for performance reasons.

If I delete this chunk of code, grunt critical runs fine, and does its thing.  I don't know if it's because of the content of the Javascript, or because it's all minimized on one line that's causing it to choke.

But if I remove it, it all works.  I can general a sample source file for you to use in testing if you want to see it hang.

**Comment by bezoerb** [comment]
@khalwat, 
i've checked the linked assets above (html + css). They are processed as expected but it seems you have already removed the failing requirejs block from there. So a sample source file for testing would be great.

**Comment by khalwat** [comment]
Sure.  Put this in your grunt file:

    critical: {
        site_index: {
            options: {
                base: '<%= pkg.dist_path %>',
                css: [
                    'http://www.crushlivepoker.com/site/css/site.combined.min.css',
                ],
                width: 960,
                height: 900
            },
            src: 'http://www.crushlivepoker.com/',
            dest: 'site_index_critical.min.css'
        },

...or curl -O http://www.crushlivepoker.com/ and plug that resulting html file in for the src:

It'll fail because of the first script tag, which is an inlined/minimized version of RequireJS and my require-config for it.  Remove the contents of that first script tag, and it works.

**Comment by bezoerb** [comment]
hey @khalwat 
your testcase runs on master but i needed to accept an outgoing firewall request (i think it was some social stuff e.g. twitter)
On travis everything runs fine.

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
