### ISSUE TITLE
Fatal error: Callback was already called

### ISSUE THREAD

**Issue by stuartsantos** [bezoerb/grunt-critical#9]
It might be something I'm doing wrong, but for some reason, I keep getting the following message:
> Destination (html/critical/index.html) failed. undefined
File "html/critical/index.html" created.
Fatal error: Callback was already called.

My gruntfile has the following:
```javascript
critical: {
      test: {
        options: {
          base: './',
          css: [
            'min/styles.css'
          ],
          width: 320,
          height: 70
        },
        src: 'html/index.html',
        dest: 'html/critical/index.html'
      }
    }
```

Have I implemented it incorrectly? It just creates a blank file where the dest path leads to

**Comment by bezoerb** [comment]
@stuartsantos configuration looks ok but i can't verify without knowing the folder structure of your project. Have you already tried with the latest version?

**Comment by stuartsantos** [comment]
@bezoerb yep, still seeing the issue...I've switched to critical-css though, so this can be closed

**Comment by bezoerb** [comment]
This one is still a valid issue

**Comment by bezoerb** [comment]
looks like this issue comes from a wrong css path.

**Comment by bezoerb** [comment]
waiting for `critical` version bump
